apiVersion: v1
kind: ConfigMap
metadata:
  name: smarttransit-config
  namespace: smarttransit
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: smarttransit
  DB_USER: root
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: guest
  RABBITMQ_VHOST: /
  MQTT_HOST: mosquitto
  MQTT_PORT: "1883"
  OAUTH_SERVICE_URL: http://oauth:3002
  CITIZEN_SERVICE_URL: http://citizen-service:8000
  TRAFFIC_SERVICE_URL: http://traffic-service:8001
  ENV_SERVICE_URL: http://environment-service:8002
  ENVIRONMENT_SERVICE_URL: http://environment-service:8002
  PYTHON_ML_URL: http://python-ml:5000
  APP_ENV: production
---
apiVersion: v1
kind: Secret
metadata:
  name: smarttransit-secrets
  namespace: smarttransit
type: Opaque
stringData:
  DB_PASSWORD: root
  DB_PASS: root
  MYSQL_ROOT_PASSWORD: root
  RABBITMQ_PASSWORD: guest
  RABBITMQ_PASS: guest
  JWT_SECRET: super_secret_key_change_this_in_production
  JWT_REFRESH_SECRET: super_secret_refresh_key_change_this_in_production
