apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: smarttransit
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: smarttransit
data:
  memory.conf: |
    vm_memory_high_watermark.absolute = 400MB
    total_memory_available_override_value = 768MB
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: smarttransit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"

          volumeMounts:
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/conf.d/
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 10
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              memory: "384Mi"
              cpu: "200m"
            limits:
              memory: "768Mi"
              cpu: "500m"
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
